/** Twenty original short passages, five evidence-based skill checks each.
 * These are focused exercises, not substitutes for full-length ACT passages.
 */
const source = [
  {
    title: 'The Repaired Clock',
    type: 'Literary Narrative',
    text: 'When Mira brought the station clock into the workshop, she expected her grandfather to replace its scratched face. He cleaned the mechanism instead. The clock began to tick, but the scratch remained. Mira found it distracting until he explained that a former station keeper had marked the face to remember the arrival of the first evening train. That evening, she set the clock on a shelf rather than repainting it. The mark had not become prettier; it had become legible. She could now read a small piece of the station’s history in a line she had nearly erased.',
    main: [
      'Mira learns that an imperfection can preserve a meaningful history.',
      'Mira discovers that old clocks cannot be repaired.',
      'The grandfather persuades Mira to stop using clocks.',
      'A station keeper teaches Mira to paint a clock.',
    ],
    detail: [
      'What does the grandfather clean?',
      'The mechanism',
      'The shelf',
      'The station platform',
      'A paintbrush',
    ],
    inference: [
      'Mira’s decision changes because she learns the scratch’s origin.',
      'Mira decides that every damaged object should be discarded.',
      'The grandfather secretly repaints the clock.',
      'The scratch prevents the clock from keeping time.',
    ],
    word: 'legible',
    meanings: ['meaningful and understandable', 'silent', 'newly polished', 'physically smaller'],
    purpose: [
      'Explains the historical meaning Mira now sees in the mark.',
      'Introduces a new disagreement about train fares.',
      'Gives instructions for replacing the clock mechanism.',
      'Reveals that the grandfather invented the station.',
    ],
  },
  {
    title: 'The Library at Dusk',
    type: 'Social Science',
    text: 'A neighborhood library initially measured its success by the number of books borrowed. When staff extended evening hours, borrowing changed little. Attendance at homework tables, however, increased sharply. A survey found that many visitors used their own books and needed only a quiet desk. The director retained circulation figures but added counts of occupied study spaces. Neither measure alone captured the library’s role. The new report did not declare borrowing unimportant; it widened the lens. Services that had always mattered to visitors finally became visible in the statistics used to plan the next year.',
    main: [
      'A library broadens its measures to capture how visitors use it.',
      'A library concludes that books are no longer useful.',
      'Evening visitors borrow more books than morning visitors.',
      'A survey proves all libraries need identical opening hours.',
    ],
    detail: [
      'What increased sharply after evening hours were extended?',
      'Attendance at homework tables',
      'The number of books borrowed',
      'The price of library cards',
      'The number of librarians',
    ],
    inference: [
      'Stable borrowing did not mean the extended hours lacked value.',
      'The director stopped recording circulation.',
      'Every visitor came only to borrow books.',
      'The survey compared libraries in several countries.',
    ],
    word: 'lens',
    meanings: [
      'way of evaluating the library',
      'piece of glass used to read',
      'new desk lamp',
      'camera used at the entrance',
    ],
    purpose: [
      'Connects broader measurement to future planning.',
      'Rejects all numerical measures as useless.',
      'Describes how to build study tables.',
      'Explains why evening hours were canceled.',
    ],
  },
  {
    title: 'Listening to the Marsh',
    type: 'Natural Science',
    text: 'A student team placed recorders at three points in a marsh. The first recordings contained fewer bird calls near a road, and the students considered reporting fewer birds there. Their advisor asked whether traffic might hide calls from the microphones. The team repeated the recordings early on a quiet morning and also counted birds by sight. Several species appeared in both locations despite the earlier difference in audible calls. The team revised its conclusion: the first recordings measured detectable sound, not necessarily the number of birds. A silent recording was not the same thing as an empty marsh.',
    main: [
      'Researchers distinguish what an instrument detects from what exists.',
      'Traffic causes every bird species to leave a marsh.',
      'Visual observation is always more accurate than recording.',
      'The students prove that marsh birds never call in the morning.',
    ],
    detail: [
      'What additional method did the team use?',
      'Counting birds by sight',
      'Measuring road width',
      'Moving all birds away from traffic',
      'Recording only at midnight',
    ],
    inference: [
      'Traffic may have masked some calls in the initial recordings.',
      'The first recordings proved that no birds lived near the road.',
      'All bird calls were identical.',
      'The advisor rejected using any instruments.',
    ],
    word: 'detectable',
    meanings: [
      'able to be noticed or recorded',
      'permanently absent',
      'artificially created',
      'impossible to compare',
    ],
    purpose: [
      'Restates the distinction between missing evidence and confirmed absence.',
      'Introduces a different marsh for the next experiment.',
      'Provides a numerical estimate of the bird population.',
      'Explains the process of building a microphone.',
    ],
  },
  {
    title: 'A Map with Empty Spaces',
    type: 'Humanities',
    text: 'The museum’s oldest coastal map left the inland hills blank. At first, the blank space looked like a mistake to curator Owen. Letters from the mapmaker revealed a different explanation: ships had surveyed the coast carefully, but no member of the expedition had crossed the hills. Other maps of the period filled such spaces with imagined mountains. This mapmaker had chosen restraint. Owen’s exhibit label described the blank region as a boundary of knowledge rather than a boundary of land. What the map refused to show became part of what made it trustworthy.',
    main: [
      'A map’s deliberate blank space reveals its maker’s caution.',
      'The expedition proved that inland hills did not exist.',
      'Imagined mountains made historical maps more accurate.',
      'Owen redraws the entire coastline from memory.',
    ],
    detail: [
      'What source explains why the hills were left blank?',
      'Letters from the mapmaker',
      'A modern tourist brochure',
      'A ship’s grocery list',
      'A photograph taken during the expedition',
    ],
    inference: [
      'The mapmaker preferred admitting uncertainty to inventing features.',
      'The expedition crossed every hill.',
      'Owen removed the map from the exhibit.',
      'All other maps of the period left inland areas blank.',
    ],
    word: 'restraint',
    meanings: [
      'deliberate limitation of what was included',
      'physical capture of the mapmaker',
      'rapid expansion of the expedition',
      'a decorative style of lettering',
    ],
    purpose: [
      'Shows how acknowledging limits can increase credibility.',
      'States that blank maps are always more useful.',
      'Lists the instruments aboard the ships.',
      'Contradicts the letters from the mapmaker.',
    ],
  },
  {
    title: 'The Quiet Rehearsal',
    type: 'Literary Narrative',
    text: 'Eli practiced his solo louder each afternoon, certain that volume would make him sound confident. During rehearsal, the conductor asked him to play softly enough to hear the cello beside him. He missed his entrance once, then noticed that the cello’s final note was his cue. On the next attempt, their phrases fit together. The conductor offered no speech about confidence. Eli carried the discovery home and practiced with the recording turned up and his own instrument turned down. For the first time, practice felt less like announcing his presence and more like finding his place.',
    main: [
      'Eli improves by listening to how his part relates to another musician’s.',
      'Eli abandons his instrument because the solo is too difficult.',
      'The conductor values loudness above timing.',
      'A cello player takes over Eli’s solo permanently.',
    ],
    detail: [
      'What becomes Eli’s cue?',
      'The cello’s final note',
      'The audience’s applause',
      'The conductor’s speech',
      'The sound of a closing door',
    ],
    inference: [
      'Eli initially equates confidence with playing loudly.',
      'Eli had never practiced before the rehearsal.',
      'The conductor tells Eli to stop listening to the cello.',
      'The next performance takes place without a conductor.',
    ],
    word: 'phrases',
    meanings: [
      'connected musical passages',
      'written announcements',
      'pieces of furniture',
      'spoken complaints',
    ],
    purpose: [
      'Contrasts Eli’s earlier self-focused approach with a more collaborative one.',
      'Explains why the orchestra canceled its concert.',
      'Describes a new instrument that Eli purchased.',
      'Shows that Eli wants to be louder than everyone else.',
    ],
  },
  {
    title: 'The Seed Notebook',
    type: 'Natural Science',
    text: 'Two classes planted the same seed variety in identical trays. One class watered on a fixed schedule; the other watered only when the soil surface looked dry. The second class recorded its watering decisions carefully, including cloudy days when the surface dried slowly. At the end of the month, its plants varied less in height. The teacher cautioned that one comparison could not establish a universal rule. Still, the notebook made the result useful: another class could repeat the decisions rather than merely imitate the final photographs. A record of the process offered more than a picture of success.',
    main: [
      'Detailed records make a classroom growing trial useful for repetition.',
      'One trial proves that fixed watering schedules always fail.',
      'Plant photographs reveal exactly how much water was used.',
      'The two classes tested entirely different seed varieties.',
    ],
    detail: [
      'What triggered watering in the second class?',
      'The soil surface looking dry',
      'A fixed daily alarm',
      'The plants reaching an identical height',
      'A photograph from another class',
    ],
    inference: [
      'The teacher sees value in the trial without treating it as conclusive.',
      'The teacher refuses to let another class repeat the trial.',
      'Cloudy days always require more watering.',
      'The first class did not use trays.',
    ],
    word: 'universal',
    meanings: [
      'applicable to every case',
      'recorded in a notebook',
      'limited to one class',
      'visible in photographs',
    ],
    purpose: [
      'Emphasizes why procedural records can be more useful than outcome images.',
      'Gives the exact average height of the plants.',
      'Identifies the seed variety by its scientific name.',
      'Argues that successful plants should never be photographed.',
    ],
  },
  {
    title: 'The Market Route',
    type: 'Social Science',
    text: 'A town moved its Saturday market from a narrow square to a larger parking area. Vendors gained space, yet several regular shoppers stopped attending. Interviews revealed that the old square lay between the bus stop and the grocery store, while the new site required a separate trip. Organizers added a walking route with signs and coordinated market hours with the bus timetable. Attendance recovered partly, though not completely. The experience complicated the original assumption that more space automatically meant better access. A location could be roomy on a plan and inconvenient in an actual day.',
    main: [
      'Market access depends on daily travel patterns as well as physical space.',
      'The town’s shoppers wanted fewer vendors at the market.',
      'Bus travel completely explains every change in attendance.',
      'A larger parking area guarantees a successful market.',
    ],
    detail: [
      'Where was the old square located?',
      'Between the bus stop and the grocery store',
      'Inside the new parking area',
      'Beside a distant train depot',
      'At the end of a private road',
    ],
    inference: [
      'The new market location interrupted some shoppers’ existing routines.',
      'Attendance rose immediately when the market moved.',
      'All shoppers traveled by car.',
      'The organizers permanently closed the market.',
    ],
    word: 'complicated',
    meanings: [
      'made less simple or certain',
      'fully confirmed',
      'made illegal',
      'repeated word for word',
    ],
    purpose: [
      'Contrasts an attractive physical plan with practical convenience.',
      'Reveals the number of parking spaces at the market.',
      'Explains how to design a grocery store.',
      'Claims the original site was perfect in every way.',
    ],
  },
  {
    title: 'A Translator’s Margin',
    type: 'Humanities',
    text: 'Leena found three translations of the same poem on her desk. One kept the rhyme but rearranged the images. Another preserved the images but lost the regular beat. The third sounded effortless until she compared its final line with the original and found an added promise. Her instructor asked her to write what each translator had chosen to protect. Leena stopped ranking the versions from best to worst and began making notes in the margins. The exercise did not make every choice equally convincing. It made her judgments more precise by requiring her to name the tradeoff behind each one.',
    main: [
      'Leena learns to evaluate translations by examining specific tradeoffs.',
      'Leena discovers that all translations have identical meanings.',
      'Rhyme is presented as the only valid goal of translation.',
      'The instructor tells Leena never to judge a translation.',
    ],
    detail: [
      'What had the third translation added?',
      'A promise in the final line',
      'A new title for the original poet',
      'A missing page from the poem',
      'A regular beat in every line',
    ],
    inference: [
      'A translation that reads smoothly can still alter meaning.',
      'Leena decides every translation is equally convincing.',
      'The instructor forbids comparison with the original.',
      'The first translation preserves every image unchanged.',
    ],
    word: 'protect',
    meanings: [
      'preserve as a priority',
      'keep physically hidden',
      'remove from the poem',
      'prove scientifically',
    ],
    purpose: [
      'Explains how identifying tradeoffs improves judgment.',
      'Declares one translation the unquestioned winner.',
      'Gives a biography of the original poet.',
      'Shows Leena abandoning the assignment.',
    ],
  },
  {
    title: 'The Second Bridge',
    type: 'Literary Narrative',
    text: 'On his first model bridge, Arun used every piece of wood in the kit. It looked sturdy, but the center sagged under the test weight. His sister pointed to the unused drawing sheet and suggested planning the next attempt. Arun sketched triangles, crossing out several designs before choosing one with fewer pieces. The second bridge held the weight. He kept the first bridge beside it, not as a warning against failure but as a reminder of how quickly he had mistaken busyness for care. The scraps on the table no longer seemed like wasted material.',
    main: [
      'Arun learns that deliberate planning can matter more than using many materials.',
      'Arun proves that heavier bridges always hold more weight.',
      'His sister constructs both bridges without his help.',
      'The kit lacks enough wood to build any working bridge.',
    ],
    detail: [
      'What did Arun sketch before his second attempt?',
      'Triangles',
      'A timetable',
      'A map of the neighborhood',
      'A list of test weights',
    ],
    inference: [
      'Arun keeps the first bridge because it records a useful lesson.',
      'Arun plans to enter the broken bridge in a contest.',
      'The second bridge uses more wood than the first.',
      'His sister advises him never to draw plans.',
    ],
    word: 'sturdy',
    meanings: ['strongly built', 'brightly colored', 'unusually expensive', 'easy to fold'],
    purpose: [
      'Shows that using fewer pieces no longer feels wasteful to Arun.',
      'Explains why all the scraps were discarded.',
      'Introduces the rules of a bridge competition.',
      'Suggests the second bridge has just collapsed.',
    ],
  },
  {
    title: 'The Cooling Roofs',
    type: 'Natural Science',
    text: 'Students compared afternoon temperatures beneath two model roofs, one pale and one dark. The pale roof stayed cooler in direct sunlight. A week later, they repeated the trial in shade and found a much smaller difference. Their report emphasized the role of lighting conditions rather than treating roof color as an isolated cause with an unchanging effect. They also noted that the models lacked ventilation and insulation found in real buildings. The comparison suggested a direction for further testing, not a complete building recommendation. Small models could open a question without settling every part of it.',
    main: [
      'Students interpret a model result cautiously by considering conditions and limits.',
      'The students establish that dark roofs are always cooler.',
      'Roof color is shown to have identical effects in sunlight and shade.',
      'The model roofs reproduce every feature of actual buildings.',
    ],
    detail: [
      'Under what condition was the temperature difference smaller?',
      'In shade',
      'In direct sunlight',
      'During a snowstorm',
      'Inside a heated oven',
    ],
    inference: [
      'Lighting conditions affected the observed difference between roof colors.',
      'The report recommends a color for every building.',
      'Ventilation was identical to that of a real house.',
      'The experiment measured electricity costs directly.',
    ],
    word: 'isolated',
    meanings: [
      'considered apart from other influences',
      'located on an island',
      'colored with pale paint',
      'measured without any instruments',
    ],
    purpose: [
      'Summarizes the exploratory value and limits of a model.',
      'Provides directions for installing a real roof.',
      'States that the students have no further questions.',
      'Claims that all models are useless.',
    ],
  },
  {
    title: 'The Mended Banner',
    type: 'Humanities',
    text: 'The festival committee asked an artist to restore a faded banner. Several members wanted every patch replaced so it would resemble the original design. The artist instead proposed retaining two repairs made by volunteers decades earlier. Their mismatched threads documented how the festival had survived a period with little money. After discussion, the committee approved a label explaining the repairs and replaced only fabric too weak to hang safely. The result was not a return to a single moment in the past. It presented the banner as something that had continued to gather history.',
    main: [
      'A restoration preserves evidence of the banner’s continuing use.',
      'The artist refuses to repair any weak fabric.',
      'The committee decides to make an entirely new banner.',
      'Mismatched thread proves that the festival was never held.',
    ],
    detail: [
      'Which fabric was replaced?',
      'Fabric too weak to hang safely',
      'Every patch made by volunteers',
      'Only the newest thread',
      'All fabric of the original color',
    ],
    inference: [
      'The committee comes to value some visible repairs as historical evidence.',
      'The repairs were made by the artist that morning.',
      'The banner is restored without any discussion.',
      'The explanatory label hides the existence of repairs.',
    ],
    word: 'documented',
    meanings: [
      'provided evidence of',
      'removed all signs of',
      'predicted with certainty',
      'made more expensive',
    ],
    purpose: [
      'Describes the banner as an object shaped by multiple periods.',
      'Gives a date for the next festival.',
      'Rejects the committee’s approved plan.',
      'Explains a particular stitching technique.',
    ],
  },
  {
    title: 'The Shared Tool Shed',
    type: 'Social Science',
    text: 'A neighborhood opened a tool shed where residents could borrow equipment. At first, volunteers required a lengthy form for every loan. The form produced detailed records but discouraged short visits. After a month, the volunteers reduced it to the borrower’s contact information, the item, and the return date. They kept a separate log for maintenance problems. Loans increased, while overdue returns changed little. The simpler process did not eliminate responsibility; it placed the essential questions where people could answer them quickly. The shed became easier to use without abandoning its basic safeguards.',
    main: [
      'A borrowing process becomes more usable while retaining essential accountability.',
      'The neighborhood eliminates all records of tool loans.',
      'Long forms prevent every overdue return.',
      'Residents stop borrowing tools after the form is shortened.',
    ],
    detail: [
      'What received a separate log?',
      'Maintenance problems',
      'Residents’ favorite colors',
      'Weather forecasts',
      'The purchase price of every home',
    ],
    inference: [
      'Some information on the original form was unnecessary for routine borrowing.',
      'Shortening the form greatly increased overdue returns.',
      'The shed stopped asking for return dates.',
      'The volunteers prohibited brief visits.',
    ],
    word: 'essential',
    meanings: [
      'necessary for the purpose',
      'difficult to understand',
      'kept secret',
      'unrelated to the task',
    ],
    purpose: [
      'Summarizes the balance between convenience and safeguards.',
      'Explains why the shed was closed.',
      'Lists every tool available to borrow.',
      'Claims that volunteers no longer have any duties.',
    ],
  },
  {
    title: 'The Wrong Platform',
    type: 'Literary Narrative',
    text: 'Sofia arrived early and stood confidently on the platform she remembered from last year. The departure board listed her train elsewhere. She checked her ticket twice, hoping the board would change, before asking an attendant. The route had moved during repairs. On the correct platform, she noticed a small sign she had passed without reading. She had been looking for familiar landmarks so intently that she had ignored new information. When her younger cousin arrived, Sofia pointed first to the board. Remembering the station was useful, she told him, but reading it was better.',
    main: [
      'Sofia learns to check current information instead of relying only on memory.',
      'Sofia misses her train because she arrives late.',
      'The attendant sends Sofia to the wrong station.',
      'The station has removed all signs during repairs.',
    ],
    detail: [
      'Why had the route moved?',
      'Because of repairs',
      'Because Sofia bought a different ticket',
      'Because the train was canceled',
      'Because the board had stopped working',
    ],
    inference: [
      'Sofia’s confidence initially makes her overlook relevant signs.',
      'The departure board eventually changes to match her memory.',
      'Her cousin knows the station better than the attendant.',
      'Sofia refuses to ask anyone for help.',
    ],
    word: 'intently',
    meanings: [
      'with concentrated attention',
      'by complete accident',
      'in a playful manner',
      'only very rarely',
    ],
    purpose: [
      'States the lesson Sofia draws from the experience.',
      'Reveals that the correct platform is still unknown.',
      'Describes the train’s mechanical problems.',
      'Suggests that memory has no value in any situation.',
    ],
  },
  {
    title: 'The Uneven Orchard',
    type: 'Natural Science',
    text: 'An orchard manager noticed that trees along one edge produced fewer apples. Before changing the fertilizer, she mapped shade during the day. The low-yield trees spent more time beneath a neighboring ridge’s shadow. She also sampled the soil and found similar nutrient levels across the orchard. These observations did not prove that shade was the only cause, but they made additional fertilizer a less obvious first response. She planned a comparison of light exposure and fruit growth over the next season. The pattern on the harvest sheet had become a question she could investigate.',
    main: [
      'An orchard manager gathers evidence before choosing a response to low yields.',
      'Fertilizer is proven never to affect apple production.',
      'All trees in the orchard receive identical light.',
      'The manager removes the ridge after one observation.',
    ],
    detail: [
      'What was similar across the orchard?',
      'Soil nutrient levels',
      'Time spent in shade',
      'The number of apples on every tree',
      'The height of the neighboring ridge',
    ],
    inference: [
      'Light exposure is a plausible factor worth testing further.',
      'The observations establish shade as the only possible cause.',
      'The manager had already doubled the fertilizer.',
      'Soil sampling showed that no nutrients were present.',
    ],
    word: 'yield',
    meanings: ['amount produced', 'willingness to surrender', 'tree height', 'soil color'],
    purpose: [
      'Shows the shift from noticing a pattern to planning an investigation.',
      'Gives the results of the following season.',
      'States that the manager abandoned the orchard.',
      'Proves that every tree needs the same treatment.',
    ],
  },
  {
    title: 'The Museum Bench',
    type: 'Humanities',
    text: 'A designer placed a bench in front of a large painting. The curator worried that seated visitors would block the room, but observations showed a different pattern. People who sat often stayed longer and then moved closer to inspect details. Other visitors could still pass along either side. The museum kept the bench and measured the clear space around it before adding seats elsewhere. Furniture had changed the pace of looking. The bench did not explain the painting, but it gave visitors time to notice what a hurried glance had missed.',
    main: [
      'Seating can change how visitors engage with an artwork.',
      'The bench prevents visitors from approaching the painting.',
      'The curator decides that museums should remove all furniture.',
      'The painting becomes easier to understand because its label is rewritten.',
    ],
    detail: [
      'What did seated visitors often do afterward?',
      'Move closer to inspect details',
      'Leave without looking at the painting',
      'Move the bench into another room',
      'Ask the museum to close the gallery',
    ],
    inference: [
      'The curator’s initial concern was not fully supported by observation.',
      'The bench blocked both sides of the room.',
      'Every visitor spent the same amount of time seated.',
      'The museum added seats without considering space.',
    ],
    word: 'pace',
    meanings: [
      'speed or rhythm',
      'price of admission',
      'distance between cities',
      'quality of the paint',
    ],
    purpose: [
      'Explains how the bench supports attention without interpreting the art.',
      'Describes the artist’s original plan for the room.',
      'Claims that labels are unnecessary in all museums.',
      'Reveals that the painting was moved outside.',
    ],
  },
  {
    title: 'A Record of Rain',
    type: 'Social Science',
    text: 'For years, a volunteer wrote daily rainfall measurements in a notebook. A regional researcher found the record valuable because it covered a valley with few official gauges. One winter, several pages were blank while the volunteer was away. The researcher preserved those gaps rather than entering zeros. Zero would mean that someone had observed no rain; a blank meant no observation was available. The distinction affected comparisons with nearby stations. An incomplete record could still be useful, provided its missing pieces were not disguised as measurements.',
    main: [
      'A researcher distinguishes missing observations from measured zeros.',
      'The notebook proves the valley had no winter rain.',
      'All unofficial weather records are rejected.',
      'The volunteer measured rainfall at every regional station.',
    ],
    detail: [
      'Why were several pages blank?',
      'The volunteer was away',
      'The valley had no rainfall',
      'The notebook was written only in summer',
      'Official gauges had replaced every local record',
    ],
    inference: [
      'Entering zeros in the gaps could distort later comparisons.',
      'Every blank page represents a dry day.',
      'The researcher destroys the incomplete notebook.',
      'Nearby stations recorded exactly the same rainfall each day.',
    ],
    word: 'preserved',
    meanings: [
      'kept without filling in or changing',
      'converted into zeros',
      'published as certain facts',
      'removed from the record',
    ],
    purpose: [
      'States the condition under which incomplete data remain useful.',
      'Gives the valley’s average yearly rainfall.',
      'Argues that researchers should never compare stations.',
      'Claims that missing records can always be reconstructed exactly.',
    ],
  },
  {
    title: 'The Pottery Lesson',
    type: 'Literary Narrative',
    text: 'June wanted every bowl to match the example at the front of the class. She pushed harder whenever the clay leaned, and the walls grew thin. Her teacher asked her to pause and feel where the thickness changed. On the next bowl, June used smaller movements. It was still uneven, but it held its shape. She wrote the teacher’s advice beside a sketch of the bowl: notice before correcting. The page did not contain a perfect design. It contained a method she could carry to the next attempt.',
    main: [
      'June learns a more observant and controlled approach to shaping clay.',
      'June produces a perfect bowl on her first attempt.',
      'The teacher tells June to press harder whenever clay leans.',
      'June decides that practice cannot improve pottery.',
    ],
    detail: [
      'What did June use on the next bowl?',
      'Smaller movements',
      'A different teacher',
      'A metal frame inside the clay',
      'A pre-made bowl hidden underneath',
    ],
    inference: [
      'June’s earlier forceful corrections contributed to the thin walls.',
      'The teacher values copying the example more than observation.',
      'The second bowl collapses immediately.',
      'June refuses to make notes about the lesson.',
    ],
    word: 'controlled',
    meanings: [
      'carefully regulated',
      'entirely accidental',
      'as forceful as possible',
      'done without attention',
    ],
    purpose: [
      'Emphasizes a reusable process rather than a flawless result.',
      'Explains how the example bowl was manufactured.',
      'Shows that June has finished learning pottery.',
      'Introduces a competition between classmates.',
    ],
  },
  {
    title: 'The Night Window',
    type: 'Natural Science',
    text: 'A class watched moths near two windows, one brightly lit and one dark. More moths appeared near the lit window during the observation period. Before writing that light increased the local moth population, a student suggested that it might simply draw existing moths toward the window. The class added counts at several nearby unlit locations. Their teacher praised the revised plan because it separated attraction from a change in total numbers. The first observation had shown a local concentration. Explaining that concentration required looking beyond the brightest spot.',
    main: [
      'Students refine an explanation by distinguishing attraction from population growth.',
      'Bright windows are shown to create new moths immediately.',
      'The class proves that moths never visit dark places.',
      'The teacher rejects counting moths at nearby sites.',
    ],
    detail: [
      'Where did the class add counts?',
      'Several nearby unlit locations',
      'Only inside the bright room',
      'A different country',
      'The same lit window at the same instant',
    ],
    inference: [
      'More moths at one window need not mean more moths overall.',
      'The observation proves that light has no effect on moth behavior.',
      'No moths were present anywhere before the lights were switched on.',
      'All counts were made during daylight.',
    ],
    word: 'concentration',
    meanings: [
      'a gathering in a limited area',
      'a period of careful studying',
      'the total age of the moths',
      'the brightness of all windows combined',
    ],
    purpose: [
      'Explains why broader observation is needed to interpret a local pattern.',
      'Describes how to install the classroom windows.',
      'Concludes that the revised plan has already failed.',
      'States that the brightest place always has the largest population.',
    ],
  },
  {
    title: 'The Poster Archive',
    type: 'Humanities',
    text: 'An archivist found theater posters with handwritten changes to performance dates. A collector offered cleaner copies, suggesting that the marked posters were less attractive. The archivist accepted the clean copies but kept the altered ones too. Comparing them showed when storms had interrupted the season and which performances had been rescheduled. The handwriting turned advertisements into records of adaptation. In the exhibition, the pairs appeared side by side. Visitors could see both the season as planned and the season as it had actually unfolded.',
    main: [
      'Altered posters preserve information that clean copies alone cannot show.',
      'The archivist rejects every clean copy offered by the collector.',
      'Handwriting makes all historical documents worthless.',
      'The theater never changed its performance schedule.',
    ],
    detail: [
      'What had been changed by hand?',
      'Performance dates',
      'The archivist’s job title',
      'The color of the theater walls',
      'The number of seats in the exhibition',
    ],
    inference: [
      'The archivist values the marked posters for evidence beyond appearance.',
      'The collector wrote all the date changes.',
      'The exhibition displays only unmarked posters.',
      'Storms improved attendance at every performance.',
    ],
    word: 'adaptation',
    meanings: [
      'adjustment to changed circumstances',
      'exact repetition of an original plan',
      'removal of every advertisement',
      'a newly written play',
    ],
    purpose: [
      'Clarifies what comparing the two versions lets visitors understand.',
      'Lists the names of the actors in the season.',
      'Explains why the theater stopped printing posters.',
      'Claims that plans never influence actual events.',
    ],
  },
  {
    title: 'The Shortcut Survey',
    type: 'Social Science',
    text: 'A campus committee considered paving a narrow dirt track across a lawn. A survey asked whether students wanted a new path, and most respondents said yes. A second question asked which route they used during rain. Many chose an existing covered walkway instead. The committee studied both responses before deciding where to improve drainage and where to add paving. Preference depended partly on the conditions under which people traveled. A single yes-or-no answer had identified demand, but it had not yet described the problem the path needed to solve.',
    main: [
      'Follow-up questions reveal conditions that matter to a planning decision.',
      'The first survey proves that no new path is wanted.',
      'Students use the dirt track equally often in all weather.',
      'The committee decides surveys cannot provide useful information.',
    ],
    detail: [
      'Which route did many respondents use during rain?',
      'An existing covered walkway',
      'Only the dirt track',
      'A closed service tunnel',
      'A path through a neighboring building’s roof',
    ],
    inference: [
      'Weather affects some students’ choice of route.',
      'Every respondent changes routes in exactly the same way.',
      'The committee paves the entire lawn immediately.',
      'The second question repeats the first without adding information.',
    ],
    word: 'demand',
    meanings: [
      'interest in or need for a path',
      'an official order to close the campus',
      'the price of paving materials',
      'the time required to finish the survey',
    ],
    purpose: [
      'Distinguishes evidence of interest from a full understanding of the need.',
      'Gives the final cost of the proposed path.',
      'Argues that yes-or-no questions are always useless.',
      'Reveals that the committee ignored both surveys.',
    ],
  },
];

export const readingSets = source.map((s) => {
  if (s.title === 'The Pottery Lesson')
    s.text = s.text.replace('smaller movements', 'smaller, controlled movements');
  if (!s.text.toLowerCase().includes(s.word.toLowerCase()))
    throw new Error(`Missing vocabulary: ${s.title}: ${s.word}`);
  const options = (values, evidence) =>
    values.map((v, i) => [
      v,
      i === 0
        ? `Supported by the passage: ${evidence}`
        : `This choice is not supported. ${evidence}`,
    ]);
  return {
    title: s.title,
    type: s.type,
    text: s.text,
    questions: [
      {
        topic: 'main idea',
        prompt: 'Which statement best expresses the passage’s central idea?',
        options: options(s.main, s.main[0]),
      },
      {
        topic: 'detail',
        prompt: s.detail[0],
        options: options(s.detail.slice(1), `The passage specifies ${s.detail[1].toLowerCase()}.`),
      },
      {
        topic: 'inference',
        prompt: 'Which conclusion is best supported by the passage?',
        options: options(s.inference, s.inference[0]),
      },
      {
        topic: 'vocabulary in context',
        prompt: `As used in this passage, “${s.word}” most nearly means:`,
        options: options(s.meanings, `In context, “${s.word}” means ${s.meanings[0]}.`),
      },
      {
        topic: 'function',
        prompt: 'What is the primary function of the passage’s final sentence?',
        options: options(s.purpose, s.purpose[0]),
      },
    ],
  };
});
