-- 0004 — redeeming a code, and the two things that have to be atomic about it.
--
-- 0003 created `redemption_codes` and `redemptions`. This adds the attempt log
-- the rate limiter counts, and the one function that turns "this code is
-- valid" into "this account is Pro" without a gap in the middle for a second
-- request to slip through.
--
-- Why a function rather than three statements in the Edge Function: a code
-- with `max_uses = 1` handed to two people who paste it at the same moment
-- would otherwise pass the check twice, because between reading `uses` and
-- writing `uses + 1` there is a window, and over the network that window is
-- milliseconds wide rather than microseconds. Doing the increment as a
-- conditional UPDATE inside a single statement closes it: Postgres serialises
-- the row, and the second caller sees the already-incremented value and gets
-- no row back. The whole claim then rides in one transaction, so a failure
-- after the increment cannot leave a used-up code with nobody holding it.
--
-- Re-runnable, matching 0001 and 0003.

-- ------------------------------------------------------------ attempt log
--
-- Only failures need to be here for rate limiting to work, but successes are
-- logged too: a burst of five successes from one account is as interesting as
-- a burst of five failures, and a log that only records the boring half is
-- useless the one time somebody asks what happened.

create table if not exists public.redemption_attempts (
  id      bigint generated always as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  at      timestamptz not null default now(),
  ok      boolean not null default false
);

create index if not exists redemption_attempts_user_at_idx
  on public.redemption_attempts (user_id, at desc);

-- RLS on, no policies: the browser has no business reading or writing this.
-- Handing a client its own attempt log would also hand it a way to clear the
-- rate limiter, which is the one thing the log exists to prevent.
alter table public.redemption_attempts enable row level security;

-- ------------------------------------------------------ the hash format
--
-- `redemption_codes.code_hash` holds a self-describing string:
--
--     pbkdf2-sha256$<iterations>$<salt-base64>$<hash-base64>
--
-- rather than a bare digest, so the parameters travel with the value and a
-- future change of cost or algorithm does not invalidate existing rows.
--
-- PBKDF2 over bcrypt for one specific reason: it is in Web Crypto, which
-- means `scripts/make-code.mjs` can produce the hash on your own machine with
-- no dependency to install, and the Edge Function can verify it with no
-- dependency either. The plaintext therefore never has to be typed anywhere
-- but your terminal and your password manager — in particular it never goes
-- through the Supabase SQL editor, which keeps a query history.
--
-- The iteration count is deliberately moderate rather than maximal. A slow KDF
-- exists to make guessing a *low-entropy* secret expensive; these codes carry
-- 125 bits from a CSPRNG, so no iteration count is what stands between an
-- attacker and the plaintext — the entropy is. Cranking it higher would only
-- hand anyone with an account a way to burn a second of server CPU per
-- request.

comment on column public.redemption_codes.code_hash is
  'pbkdf2-sha256$<iterations>$<salt-b64>$<hash-b64>. Generated by scripts/make-code.mjs; the plaintext is never stored anywhere.';

-- ----------------------------------------------------------- the claim
--
-- Takes an already-verified code id. The hash comparison happens in the Edge
-- Function, because this function must not receive the plaintext: anything
-- passed as a SQL argument can end up in `pg_stat_statements`, in a slow-query
-- log, or in an error message.
--
-- Returns one of 'ok' | 'already' | 'exhausted' rather than raising, because
-- all three are ordinary answers a person needs phrased for them, not faults.

create or replace function public.claim_code(p_code_id uuid, p_user_id uuid)
  returns text
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_grants text;
begin
  -- Already redeemed by this account. Not an error — someone pasting their own
  -- code into a second device is doing something completely reasonable — but it
  -- must not consume a second use.
  if exists (select 1 from public.redemptions where code_id = p_code_id and user_id = p_user_id) then
    return 'already';
  end if;

  /* The conditional increment *is* the check. Reading `uses` first and
     deciding afterwards is the race this function exists to remove. */
  update public.redemption_codes
     set uses = uses + 1
   where id = p_code_id
     and (max_uses is null or uses < max_uses)
     and (expires_at is null or expires_at > now())
  returning grants into v_grants;

  if v_grants is null then
    return 'exhausted';
  end if;

  insert into public.redemptions (code_id, user_id) values (p_code_id, p_user_id);

  /* `current_period_end = null` is how "does not expire" is spelled — see the
     note in src/lib/entitlements.ts, where a null period end on an active row
     is the permanent grant. `trial_ends_at` is cleared because a trial that is
     still counting down under a permanent grant would put a countdown pill in
     the header of somebody who has already been given the thing. */
  insert into public.entitlements (user_id, plan, status, trial_ends_at, current_period_end, source, updated_at)
  values (p_user_id, v_grants, 'active', null, null, 'code', now())
  on conflict (user_id) do update
    set plan               = excluded.plan,
        status             = excluded.status,
        trial_ends_at      = null,
        current_period_end = null,
        source             = 'code',
        updated_at         = now();

  return 'ok';
end;
$$;

/* Not callable from a browser, at any tier.
 *
 * `security definer` means this function runs as its owner and can write the
 * one table RLS exists to keep clients out of. Left executable by
 * `authenticated`, it would be exactly the "set my own plan to pro" endpoint
 * that 0003 went to some trouble not to provide — it takes a code id, and code
 * ids are not secret. The secret is the code, and only the Edge Function ever
 * sees one. */
revoke all on function public.claim_code(uuid, uuid) from public;
revoke all on function public.claim_code(uuid, uuid) from anon;
revoke all on function public.claim_code(uuid, uuid) from authenticated;
grant execute on function public.claim_code(uuid, uuid) to service_role;
